"""Tests for :mod:`scripts.revamp_commit_guard` (T1 nit closeout)."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GUARD_SCRIPT = REPO_ROOT / "scripts" / "revamp_commit_guard.py"

sys.path.insert(0, str(REPO_ROOT))
from scripts.revamp_commit_guard import (  # noqa: E402
    REJECT_THRESHOLD,
    RESULT_OK,
    RESULT_REJECT,
    RESULT_WARN,
    WARN_THRESHOLD,
    _is_autogenerated,
    evaluate,
)


def _numstat(rows: list[tuple[int, int, str]]) -> str:
    return "\n".join(f"{a}\t{r}\t{p}" for a, r, p in rows)


# --- pure classification ------------------------------------------------


def test_under_warn_threshold_is_ok() -> None:
    r = evaluate(_numstat([(50, 30, "src/a.py"), (100, 0, "src/b.py")]))
    assert r.total_loc == 180
    assert r.classification == RESULT_OK
    assert r.exit_code == 0


def test_at_warn_threshold_warns() -> None:
    r = evaluate(_numstat([(WARN_THRESHOLD, 0, "src/a.py")]))
    assert r.classification == RESULT_WARN
    assert r.exit_code == 0


def test_just_below_reject_still_warns() -> None:
    r = evaluate(_numstat([(REJECT_THRESHOLD - 1, 0, "src/a.py")]))
    assert r.classification == RESULT_WARN
    assert r.exit_code == 0


def test_over_reject_threshold_rejects() -> None:
    r = evaluate(_numstat([(REJECT_THRESHOLD, 0, "src/a.py"), (50, 0, "src/b.py")]))
    assert r.classification == RESULT_REJECT
    assert r.exit_code == 1


def test_autogenerated_files_are_skipped() -> None:
    r = evaluate(_numstat([
        (5000, 0, "package-lock.json"),
        (200, 0, "apps/setup-center/package-lock.json"),
        (300, 0, "docs/revamp/LOC_BASELINE.json"),
        (40, 0, "icon.svg"),
        (10, 0, "poetry.lock"),
        (100, 50, "src/real.py"),
    ]))
    assert r.total_loc == 150
    assert r.classification == RESULT_OK
    assert r.counted_files == ["src/real.py"]
    assert "package-lock.json" in r.skipped_files


def test_binary_diff_marker_is_ignored() -> None:
    r = evaluate("-\t-\tbinary/blob.bin\n10\t0\tsrc/real.py")
    assert r.total_loc == 10


def test_autogenerated_helper_classifies_paths() -> None:
    assert _is_autogenerated("package-lock.json")
    assert _is_autogenerated("apps/setup-center/package-lock.json")
    assert _is_autogenerated("docs/revamp/LOC_BASELINE.json")
    assert _is_autogenerated("assets/icon.svg")
    assert _is_autogenerated("poetry.lock")
    assert not _is_autogenerated("src/openakita/foo.py")
    assert not _is_autogenerated("docs/architecture.md")
    assert not _is_autogenerated("data/orgs_v2.json")


# --- CLI subprocess path against a real tmp git repo --------------------


def _init_repo(path: Path) -> None:
    subprocess.run(["git", "init", "-q", str(path)], check=True)
    for key, val in (
        ("user.email", "guard@test"),
        ("user.name", "guard"),
        ("commit.gpgsign", "false"),
    ):
        subprocess.run(["git", "-C", str(path), "config", key, val], check=True)


def _run_guard(repo: Path) -> tuple[int, str]:
    proc = subprocess.run(
        [sys.executable, str(GUARD_SCRIPT), "--staged", "--repo", str(repo)],
        capture_output=True, text=True, check=False,
    )
    return proc.returncode, proc.stdout


def _stage_file(repo: Path, name: str, n_lines: int) -> None:
    (repo / name).write_text(
        "\n".join(f"line_{i}" for i in range(n_lines)) + "\n", encoding="utf-8"
    )
    subprocess.run(["git", "-C", str(repo), "add", name], check=True)


def test_cli_reports_ok_under_threshold(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _stage_file(tmp_path, "small.py", 50)
    code, out = _run_guard(tmp_path)
    assert code == 0
    assert "ok:" in out
    assert "50 hand-written LOC" in out


def test_cli_warns_between_thresholds(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _stage_file(tmp_path, "mid.py", (WARN_THRESHOLD + REJECT_THRESHOLD) // 2)
    code, out = _run_guard(tmp_path)
    assert code == 0
    assert "WARN:" in out


def test_cli_rejects_over_threshold(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _stage_file(tmp_path, "big.py", REJECT_THRESHOLD + 25)
    code, out = _run_guard(tmp_path)
    assert code == 1
    assert "REJECT:" in out


def test_cli_skips_autogenerated_lockfile(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _stage_file(tmp_path, "package-lock.json", REJECT_THRESHOLD + 100)
    _stage_file(tmp_path, "small.py", 20)
    code, out = _run_guard(tmp_path)
    assert code == 0
    assert "ok:" in out
    assert "package-lock.json" in out
