"""
File serving endpoint for desktop chat.

Allows the desktop frontend to access workspace files (images, documents, etc.)
generated by agent tools like deliver_artifacts, generate_image, etc.

Security: Only serves files under the current workspace directory.
"""

import logging
import mimetypes
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, JSONResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/files", tags=["files"])

# Path values that the desktop chat / file picker sends to mean "show me
# the workspace root listing" rather than "serve a specific file". The
# v10 exploratory report (issue #15) flagged ``GET /api/files?path=.``
# returning 404 as unintuitive; treat these as a directory-listing
# request against the workspace root.
_WORKSPACE_ROOT_ALIASES: frozenset[str] = frozenset({"", ".", "./", "/"})
_MAX_DIR_LISTING_ENTRIES = 500


def _get_workspace_root(request: Request, conversation_id: str = "") -> Path:
    """Get the workspace root directory from the running agent."""
    if conversation_id:
        session_manager = getattr(request.app.state, "session_manager", None)
        if session_manager is None:
            raise HTTPException(status_code=503, detail="Session manager unavailable")
        session = session_manager.get_session(
            channel="desktop",
            chat_id=conversation_id,
            user_id="desktop_user",
            create_if_missing=False,
        )
        if session is None:
            raise HTTPException(status_code=404, detail="Session not found")
        from ...core.working_directory import session_working_directory

        return session_working_directory(session, require_available=True)
    agent = getattr(request.app.state, "agent", None)

    if agent is not None:
        # Try to get workspace_dir from agent
        ws_dir = getattr(agent, "workspace_dir", None) or getattr(agent, "_workspace_dir", None)
        if ws_dir:
            return Path(ws_dir)

    # Fallback: try settings
    try:
        from openakita.core.settings import settings

        if settings.workspace_dir:
            return Path(settings.workspace_dir)
    except Exception:
        pass

    # Last resort: current working directory
    return Path.cwd()


@router.get("")
async def serve_file(
    request: Request,
    path: str = "",
    inline: str = "",
    conversation_id: str = "",
):
    """
    Serve a file from the workspace directory.

    Query parameter `path` can be relative to workspace root or absolute.
    Example: /api/files?path=data/temp/image.png
    Example: /api/files?path=D:/coder/myagent/data/temp/image.png

    Query parameter ``inline`` (``1``/``true``): force an ``inline``
    ``Content-Disposition`` so the browser renders the file in-page (e.g. a
    PDF in an ``<iframe>`` for the deliverable preview modal) instead of
    triggering a download. Defaults off; download flows omit it and keep the
    historical ``attachment`` disposition for non-media types.

    When ``path`` is empty, ``.``, ``./``, or ``/``, the endpoint
    returns a JSON listing of the workspace root instead of a file
    response. The frontend file picker expects "list the root" to
    work without a special endpoint.
    """
    try:
        workspace = _get_workspace_root(request, conversation_id)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc

    if (path or "").strip() in _WORKSPACE_ROOT_ALIASES:
        return _list_directory(workspace, workspace)

    # Handle both relative and absolute paths
    requested = Path(path)
    full_path = requested if requested.is_absolute() else workspace / path

    # Resolve to prevent path traversal
    try:
        full_path = full_path.resolve()
    except (OSError, ValueError):
        raise HTTPException(status_code=400, detail="Invalid path")

    # Security: ensure the file is under workspace OR under known safe directories
    # (e.g. user home, temp dirs used by agent tools)
    # Use Path.is_relative_to() instead of string prefix matching to avoid
    # false positives (e.g. /home/user matching /home/user_docs) and
    # case-sensitivity issues on Windows.
    workspace_resolved = workspace.resolve()
    safe_roots = [workspace_resolved]
    if not conversation_id:
        # Legacy callers without a conversation scope retain the historical
        # home-directory allowance. New chat surfaces always send a scope.
        safe_roots.append(Path.home().resolve())
    if not conversation_id:
        try:
            from ...config import settings

            safe_roots.append(Path(settings.data_dir).resolve())
        except Exception:
            pass

    is_safe = any(full_path.is_relative_to(root) for root in safe_roots)
    if not is_safe:
        raise HTTPException(
            status_code=403, detail="Access denied: path outside allowed directories"
        )

    if not full_path.exists():
        raise HTTPException(status_code=404, detail=f"File not found: {path}")

    if full_path.is_dir():
        return _list_directory(full_path, workspace_resolved)

    if not full_path.is_file():
        raise HTTPException(status_code=404, detail=f"File not found: {path}")

    content_type = _guess_content_type(full_path)

    force_inline = (inline or "").strip().lower() in ("1", "true", "yes", "on")
    is_inline = force_inline or content_type.startswith(("audio/", "video/", "image/"))
    return FileResponse(
        path=str(full_path),
        media_type=content_type,
        filename=full_path.name,
        content_disposition_type="inline" if is_inline else "attachment",
    )


def _list_directory(directory: Path, workspace_root: Path) -> JSONResponse:
    """Return a directory listing as JSON.

    Only used for the workspace-root convenience alias and when the
    caller targets a directory explicitly; the security checks above
    have already constrained ``directory`` to safe roots.
    """
    try:
        entries = sorted(directory.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
    except OSError as exc:
        raise HTTPException(status_code=500, detail=f"Cannot list directory: {exc}") from exc

    items: list[dict[str, object]] = []
    for entry in entries[:_MAX_DIR_LISTING_ENTRIES]:
        try:
            stat = entry.stat()
        except OSError:
            continue
        rel = ""
        try:
            rel = entry.relative_to(workspace_root).as_posix()
        except ValueError:
            rel = entry.as_posix()
        items.append(
            {
                "name": entry.name,
                "path": rel,
                "is_dir": entry.is_dir(),
                "size": stat.st_size if entry.is_file() else 0,
                "modified": stat.st_mtime,
            }
        )
    truncated = len(entries) > _MAX_DIR_LISTING_ENTRIES
    return JSONResponse(
        {
            "directory": str(directory),
            "workspace_root": str(workspace_root),
            "items": items,
            "count": len(items),
            "truncated": truncated,
        }
    )


_MIME_FALLBACK: dict[str, str] = {
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".ogg": "audio/ogg",
    ".flac": "audio/flac",
    ".aac": "audio/aac",
    ".m4a": "audio/mp4",
    ".wma": "audio/x-ms-wma",
    ".opus": "audio/opus",
    ".mp4": "video/mp4",
    ".webm": "video/webm",
    ".mkv": "video/x-matroska",
    ".avi": "video/x-msvideo",
    ".mov": "video/quicktime",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".svg": "image/svg+xml",
    ".bmp": "image/bmp",
    ".ico": "image/x-icon",
    ".pdf": "application/pdf",
}


def _guess_content_type(path: Path) -> str:
    """Guess MIME type with a built-in fallback table for common media formats.

    Python's mimetypes module reads from the Windows registry, which can be
    unreliable (missing entries, uppercase extensions, custom associations).
    We try mimetypes first, then fall back to our own table using the
    lowercased extension.
    """
    ct, _ = mimetypes.guess_type(str(path))
    if ct:
        return ct
    ext = path.suffix.lower()
    return _MIME_FALLBACK.get(ext, "application/octet-stream")
