"""Build formatted Excel report workbooks."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from excel_formula import explain_formula
from excel_models import WorkbookPlan
from excel_style_engine import apply_table_style, apply_title_style, autofit_columns


class WorkbookBuildError(RuntimeError):
    pass


def _try_openpyxl():
    try:
        import openpyxl  # type: ignore
        from openpyxl.chart import BarChart, Reference  # type: ignore
        from openpyxl.utils import get_column_letter  # type: ignore

        return openpyxl, BarChart, Reference, get_column_letter
    except ImportError as exc:
        raise WorkbookBuildError(
            "openpyxl is required to build .xlsx reports. Install dependency group table_core."
        ) from exc


class WorkbookBuilder:
    def build(
        self,
        *,
        plan: WorkbookPlan,
        profile: dict[str, Any] | None,
        preview: dict[str, Any] | None,
        output_path: str | Path,
        audit_items: list[dict[str, Any]] | None = None,
    ) -> Path:
        openpyxl, bar_chart_cls, reference_cls, get_column_letter = _try_openpyxl()
        wb = openpyxl.Workbook()
        default = wb.active
        wb.remove(default)
        brand_color = str(plan.style.get("brand_color") or "#2563eb")

        self._write_readme(wb.create_sheet("README"), plan, profile)
        raw_rows = self._extract_rows(preview)
        self._write_table(wb.create_sheet("Raw_Data"), raw_rows, brand_color)
        clean_ws = wb.create_sheet("Clean_Data")
        self._write_table(clean_ws, raw_rows, brand_color)
        self._write_summary(wb.create_sheet("Summary"), raw_rows, brand_color, get_column_letter)
        self._write_charts(
            wb.create_sheet("Charts"), raw_rows, brand_color, bar_chart_cls, reference_cls
        )
        self._write_formula_check(wb.create_sheet("Formula_Check"), plan, brand_color)
        self._write_audit_log(wb.create_sheet("Audit_Log"), plan, audit_items or [], brand_color)

        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        wb.save(output)
        return output

    def update_audit_log(
        self,
        *,
        workbook_path: str | Path,
        plan: WorkbookPlan,
        audit_items: list[dict[str, Any]],
    ) -> Path:
        openpyxl, _, _, _ = _try_openpyxl()
        path = Path(workbook_path)
        wb = openpyxl.load_workbook(path)
        if "Audit_Log" in wb.sheetnames:
            del wb["Audit_Log"]
        ws = wb.create_sheet("Audit_Log")
        brand_color = str(plan.style.get("brand_color") or "#2563eb")
        self._write_audit_log(ws, plan, audit_items, brand_color)
        wb.save(path)
        return path

    def _extract_rows(self, preview: dict[str, Any] | None) -> list[list[Any]]:
        if not preview:
            return [["Note"], ["No source preview was available."]]
        first = next(iter(preview.values()), {})
        headers = list(first.get("headers") or [])
        rows = list(first.get("rows") or [])
        if not headers and rows:
            headers = [f"Column_{idx + 1}" for idx in range(max(len(row) for row in rows))]
        return [headers or ["Note"], *rows] if rows else [headers or ["Note"], ["No rows found"]]

    def _write_readme(self, ws, plan: WorkbookPlan, profile: dict[str, Any] | None) -> None:
        rows = [
            ["Excel Report Workbook"],
            ["Title", plan.title],
            ["Purpose", plan.purpose or "Not specified"],
            ["Generated At", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Source Workbook", plan.source_workbook_id or ""],
            ["Sheet Count", len(plan.sheets)],
            ["Important Notes", "This workbook was generated by deterministic excel-maker code."],
        ]
        if profile:
            rows.append(
                [
                    "Profiled Sheets",
                    ", ".join(sheet.get("name", "") for sheet in profile.get("sheets", [])),
                ]
            )
        for row in rows:
            ws.append(row)
        apply_title_style(ws)

    def _write_table(self, ws, rows: list[list[Any]], brand_color: str) -> None:
        for row in rows:
            ws.append(row)
        apply_table_style(ws, brand_color=brand_color)

    def _write_summary(
        self, ws, rows: list[list[Any]], brand_color: str, get_column_letter
    ) -> None:
        headers = rows[0] if rows else []
        data = rows[1:]
        ws.append(["Metric", "Value", "Formula/Source"])
        ws.append(["Row Count", len(data), "COUNTA Raw_Data rows"])
        ws.append(["Column Count", len(headers), "Header columns"])
        numeric_columns = []
        for idx, header in enumerate(headers, start=1):
            values = []
            for row in data:
                if idx - 1 < len(row):
                    try:
                        values.append(float(row[idx - 1]))
                    except (TypeError, ValueError):
                        pass
            if values:
                numeric_columns.append((idx, header))
                column_letter = get_column_letter(idx)
                end_row = max(len(data) + 1, 2)
                ws.append(
                    [
                        f"Sum: {header}",
                        sum(values),
                        f"=SUM(Clean_Data!{column_letter}2:{column_letter}{end_row})",
                    ]
                )
        if not numeric_columns:
            ws.append(["Numeric Columns", 0, "No numeric sample columns detected"])
        apply_table_style(ws, brand_color=brand_color)

    def _write_charts(
        self, ws, rows: list[list[Any]], brand_color: str, bar_chart_cls, reference_cls
    ) -> None:
        ws.append(["Chart Source", "Value"])
        ws.append(["Rows", max(len(rows) - 1, 0)])
        ws.append(["Columns", len(rows[0]) if rows else 0])
        apply_table_style(ws, brand_color=brand_color)
        chart = bar_chart_cls()
        chart.title = "Workbook Shape"
        chart.y_axis.title = "Count"
        chart.x_axis.title = "Metric"
        data = reference_cls(ws, min_col=2, min_row=1, max_row=3)
        cats = reference_cls(ws, min_col=1, min_row=2, max_row=3)
        chart.add_data(data, titles_from_data=True)
        chart.set_categories(cats)
        ws.add_chart(chart, "D2")

    def _write_formula_check(self, ws, plan: WorkbookPlan, brand_color: str) -> None:
        ws.append(["Sheet", "Cell", "Formula", "Explanation"])
        formulas = list(plan.formulas)
        if not formulas:
            ws.append(
                ["Summary", "B2", "=COUNTA(Clean_Data!A:A)-1", "统计清洗数据行数的示例公式。"]
            )
        else:
            for item in formulas:
                ws.append(
                    [
                        item.sheet,
                        item.cell,
                        item.formula,
                        item.explanation or explain_formula(item.formula),
                    ]
                )
        apply_table_style(ws, brand_color=brand_color)

    def _write_audit_log(
        self, ws, plan: WorkbookPlan, audit_items: list[dict[str, Any]], brand_color: str
    ) -> None:
        ws.append(["Severity", "Category", "Message", "Location", "Suggestion"])
        if audit_items:
            for item in audit_items:
                ws.append(
                    [
                        item.get("severity", "info"),
                        item.get("category", "general"),
                        item.get("message", ""),
                        item.get("location", ""),
                        item.get("suggestion", ""),
                    ]
                )
        else:
            ws.append(
                ["info", "build", "Workbook generated", "", "Review formulas and source ranges."]
            )
        ws.append([])
        ws.append(
            ["WorkbookPlan JSON", json.dumps(plan.model_dump(mode="json"), ensure_ascii=False)]
        )
        apply_table_style(ws, brand_color=brand_color)
        autofit_columns(ws)
