"""Whitelist operation executor for workbook plans."""

from __future__ import annotations

from typing import Any

from excel_models import WorkbookPlan, WorkbookPlanOperation

SUPPORTED_OPERATIONS = {
    "rename_column",
    "cast_type",
    "fill_missing",
    "drop_duplicates",
    "derive_column",
    "groupby",
    "pivot",
    "sort",
    "filter",
    "write_formula",
}


class OperationExecutionError(RuntimeError):
    pass


class ExcelOperationExecutor:
    """Validate and summarize safe operations.

    MVP keeps data transformation conservative. It never executes arbitrary
    Python/JS/SQL generated by a model; later phases can expand each operation.
    """

    def validate_operations(self, operations: list[WorkbookPlanOperation]) -> None:
        for operation in operations:
            if operation.op not in SUPPORTED_OPERATIONS:
                raise OperationExecutionError(f"Unsupported operation: {operation.op}")
            if (
                "code" in operation.params
                or "script" in operation.params
                or "sql" in operation.params
            ):
                raise OperationExecutionError(f"Operation {operation.op} contains executable code")

    def apply_plan(
        self, plan: WorkbookPlan, profile: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        self.validate_operations(plan.operations)
        return {
            "applied": [
                {
                    "op": operation.op,
                    "source_sheet": operation.source_sheet,
                    "target_sheet": operation.target_sheet,
                    "params": operation.params,
                    "status": "accepted",
                }
                for operation in plan.operations
            ],
            "profile_workbook_id": (profile or {}).get("workbook_id"),
            "notes": [
                "MVP validates operation safety and delegates materialization to workbook builder."
            ],
        }
