"""UI hard-contract smoke tests for fin-pulse.

These asserts mirror §11 of the plan and make sure the single-page UI
stays aligned with the avatar-studio UI Kit conventions:

* ``_assets/`` bundles the five canonical files
  (``bootstrap.js`` / ``styles.css`` / ``icons.js`` / ``i18n.js`` /
  ``markdown-mini.js``).
* The shipped ``index.html`` declares the five bundle tags verbatim,
  the five canonical ``data-theme`` / ``PluginErrorBoundary`` /
  ``TAB_IDS`` tokens, and none of the forbidden ones (SDK 0.6 paths,
  ``classList.toggle('dark-mode')``, ``ReactDOM.render``).
* The plugin manifest loads cleanly and enumerates exactly the seven
  V1.0 agent tools that ``plugin.py`` registers on ``on_load``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent.parent
UI_DIR = PLUGIN_DIR / "ui" / "dist"
ASSETS_DIR = UI_DIR / "_assets"
INDEX_HTML = UI_DIR / "index.html"
MANIFEST = PLUGIN_DIR / "plugin.json"


def test_daily_brief_html_has_report_layout() -> None:
    from finpulse_report.render import build_daily_brief

    _, html_blob, stats = build_daily_brief(
        [
            {
                "source_id": "wallstreetcn",
                "title": "美联储释放降息信号",
                "summary": "市场关注美元和人民币汇率变化。",
                "url": "https://example.com/a",
                "published_at": "2026-04-25T09:30:00",
                "ai_score": 8.2,
                "raw": {"rank": 1, "hot": 1234},
            }
        ],
        session="morning",
        top_k=20,
        lang="zh",
        generated_at="2026-04-25T08:00:00Z",
    )
    assert stats.total_selected == 1
    for token in ("AI 要点摘要", "市场脉络", "重点新闻", "Generated by Fin Pulse"):
        assert token in html_blob


def test_assets_present() -> None:
    """The five vendored UI Kit assets must live under ui/dist/_assets."""
    expected = {"bootstrap.js", "styles.css", "icons.js", "i18n.js", "markdown-mini.js"}
    actual = {p.name for p in ASSETS_DIR.iterdir() if p.is_file()}
    missing = expected - actual
    assert not missing, f"missing UI Kit assets: {missing}"


def test_sidebar_icon_present() -> None:
    """plugins/fin-pulse/icon.svg is auto-discovered by the host to render
    the sidebar app-launcher icon (see api/routes/plugins.py _ICON_NAMES).
    The file must exist, be non-trivial, and declare an <svg> root.
    Also served from ui/dist/finpulse-finance.svg so ``ui.icon`` can
    change URL when the visual mark changes.
    """
    for candidate in (
        PLUGIN_DIR / "icon.svg",
        UI_DIR / "icon.svg",
        UI_DIR / "finpulse-finance.svg",
        UI_DIR / "finpulse-brand.svg",
    ):
        assert candidate.exists(), f"icon.svg missing: {candidate}"
        blob = candidate.read_text("utf-8")
        assert "<svg" in blob and "viewBox" in blob, f"{candidate} is not a valid SVG"
        assert len(blob) > 256, f"{candidate} seems too small / empty"
    manifest = json.loads(MANIFEST.read_text("utf-8"))
    assert manifest["icon"] == "icon.svg"
    assert manifest["ui"]["icon"] == "finpulse-brand.svg", (
        "plugin.json ui.icon should cache-bust via named SVG"
    )


def test_index_html_exists_and_nonempty() -> None:
    assert INDEX_HTML.exists(), "ui/dist/index.html missing"
    html = INDEX_HTML.read_text("utf-8")
    assert len(html) > 1024, "index.html is suspiciously short"


def test_custom_time_filter_keeps_source_wall_clock_boundaries() -> None:
    """datetime-local values must stay aligned with displayed source dates."""
    html = INDEX_HTML.read_text("utf-8")

    assert "function datetimeLocalToWallClock(value, upperBound)" in html
    assert "datetimeLocalToWallClock(filters.since, false)" in html
    assert "datetimeLocalToWallClock(filters.until, true)" in html
    assert "function datetimeLocalToISO" not in html


def test_rate_limited_renders_as_cooldown_not_error() -> None:
    """NewsNow public cooldown is a retryable wait state, not a failure."""
    html = INDEX_HTML.read_text("utf-8")
    assert 'row.error_kind === "rate_limited") return "fp-pill fp-pill--cooldown"' in html
    assert '"today.drawer.status.cooldown": "冷却中 · {s}s 后可重试"' in html
    assert "const hasError = !!(row.error || row.error_kind) && !isCooldown;" in html


def test_ui_hard_contracts() -> None:
    """Every required token from §11 must appear; every forbidden must not."""
    html = INDEX_HTML.read_text("utf-8")
    required = [
        r'<script\s+src="_assets/bootstrap\.js"',
        r'<link\s+rel="stylesheet"\s+href="_assets/styles\.css"',
        r'<script\s+src="_assets/icons\.js"',
        r'<script\s+src="_assets/i18n\.js"',
        r'<script\s+src="_assets/markdown-mini\.js"',
        r'data-theme="dark"',
        r"@media\s*\(prefers-color-scheme:\s*dark\)",
        r'const\s+TAB_IDS\s*=\s*\[\s*"today"\s*,\s*"digests"\s*,\s*"radar"\s*,\s*"settings"\s*\]',
        r"const\s+TAB_ICONS\s*=",
        r"class\s+PluginErrorBoundary\s+extends\s+React\.Component",
        r'ReactDOM\.createRoot\(document\.getElementById\("root"\)\)',
        r"window\.OpenAkitaI18n\.register\(I18N_DICT\)",
        r'"tabs\.today"',
        r'"tabs\.digests"',
        r'"tabs\.radar"',
        r'"tabs\.settings"',
        r"oa-config-banner",
        r"oa-hero-title",
        r"oa-section-title",
        r"stack-layout",
        r"seg-group",
        r"seg-btn",
        r"filter-bar",
        r"oa-hint",
        r"BrandMark",
        r"api-pill",
        r"ConfirmHost",
        # P0 — api() must unwrap Bridge {ok,status,body} envelopes.
        r'"body"\s+in\s+res',
        # P0 — oaToast must send {type, body} for the host notify API.
        r"type:\s*level",
        r"body:\s*message",
        # P1 — radar editor is kept compact; hit preview grows.
        r"card--compact",
        # P1 — templated schedule buttons exist instead of window.prompt.
        r"SCHEDULE_TEMPLATES",
        r"ScheduleDialog",
        # P2 — CodeBlock component for NewsNow docker snippet.
        r"fp-codeblock",
        # P2 — Darker muted / dim tokens.
        r"--text-muted:\s*#5E3540",
        r"--text-dim:\s*#7A4E59",
    ]
    for pat in required:
        assert re.search(pat, html), f"hard contract missing: {pat}"

    forbidden = [
        r"/api/plugins/_sdk/",
        r"classList\.toggle\('dark-mode'\)",
        # Raw ReactDOM.render is forbidden; createRoot is required.
        r"ReactDOM\.render\(",
        # The fin-pulse custom event names never fired — we must not
        # register listeners for them any more.
        r'onEvent\("plugin:fin-pulse:',
        # The Settings schedule card should no longer use window.prompt
        # for mode/cron/session — replaced by ScheduleDialog.
        r'window\.prompt\("mode\s*\(daily_brief',
    ]
    for pat in forbidden:
        assert not re.search(pat, html), f"forbidden token present: {pat}"


def test_plugin_manifest_matches_tool_shape() -> None:
    manifest = json.loads(MANIFEST.read_text("utf-8"))
    assert manifest["id"] == "fin-pulse"
    assert manifest["type"] == "python"
    assert manifest["entry"] == "plugin.py"
    # Seven V1.0 agent tools — keep in lockstep with plugin.py::_tool_definitions.
    expected_tools = {
        "fin_pulse_create",
        "fin_pulse_status",
        "fin_pulse_list",
        "fin_pulse_cancel",
        "fin_pulse_settings_get",
        "fin_pulse_settings_set",
        "fin_pulse_search_news",
    }
    assert set(manifest["provides"]["tools"]) == expected_tools
    # Permissions MUST include the critical eleven.
    for perm in (
        "tools.register",
        "routes.register",
        "hooks.basic",
        "data.own",
        "channel.send",
        "brain.access",
        "config.read",
        "config.write",
    ):
        assert perm in manifest["permissions"], f"permission '{perm}' missing"


def test_fallback_modes_mirror_models_module() -> None:
    """plugin.py's _FALLBACK_MODES must stay a superset of the Phase-1b
    canonical modes so the /modes route keeps a meaningful payload even
    if the models import ever regresses.
    """
    plugin_src = (PLUGIN_DIR / "plugin.py").read_text("utf-8")
    for mode in ("daily_brief", "hot_radar", "ask_news"):
        assert f'"{mode}"' in plugin_src, f"plugin.py missing fallback mode: {mode}"


def test_ui_tabs_are_hydrated() -> None:
    """Phase 6 — each tab body must talk to the REST surface instead of
    rendering the Phase-1 placeholder. We assert that the hot-path API
    calls and the NewsNow 3-stage wizard tokens are present.
    """
    html = INDEX_HTML.read_text("utf-8")

    # Today tab talks to /articles + /ingest and uses the new
    # /sources route to hydrate its dropdown (P0 — avoids drift with
    # finpulse_models.SOURCE_DEFS).
    assert 'api("GET", "/articles"' in html
    # The Today tab now calls /ingest via a dynamic ``path`` variable so
    # the same code path covers both bulk and single-source runs. We
    # still require either the literal POST string or the path-shaped
    # call to prove the wiring is present.
    assert 'api("POST", "/ingest"' in html or 'api("POST", path' in html, (
        "Today tab missing POST /ingest call"
    )
    assert "/ingest/source/" in html, (
        "Today tab must expose the single-source /ingest/source/{id} call"
    )
    assert 'api("GET", "/sources"' in html

    # Digests workbench lists + runs + iframes html blobs.
    assert 'api("GET", "/digests' in html
    assert 'api("POST", "/digest/run"' in html
    assert "/digests/" in html and "/html" in html
    assert "HTML 报表即时预览" in html
    assert "digest-workbench" in html
    assert "srcDoc={previewHtml" in html
    assert 'api("DELETE", "/digests/"' in html
    assert "强制先抓取最新资讯" in html
    # Built-in morning / noon / evening report cards must default to
    # pre-ingest = on so a fresh install never publishes a stale brief.
    assert "preIngest: true" in html, "default reportConfigs / customDraft must opt into preIngest"
    # Radar tab: forceRefresh useState must default to true so the
    # first run after install pulls fresh hot-list articles.
    assert "useState(true)" in html, "RadarTab.forceRefresh initial state must default to true"
    assert "自定义报表工作台" in html
    assert "自定义报表计划" in html
    assert 'api("GET", "/report-plans"' in html
    assert 'api("PUT", "/report-plans/"' in html
    assert 'api("POST", "/report-plans/"' in html
    assert 'api("DELETE", "/report-plans/"' in html
    assert "source_ids" in html
    assert "morning:" in html and "noonIcon:" in html and "eveningIcon:" in html

    # Radar workbench exercises evaluate + config save + alert execution paths.
    assert 'api("POST", "/radar/evaluate"' in html
    assert "radar_rules" in html
    assert 'api("POST", "/hot_radar/run"' in html
    assert "雷达预警工作台" in html
    assert "radar-workbench" in html
    assert "通知通道" in html
    assert "radar-rule-help" in html
    assert "radar-report-hero" in html
    assert "雷达命中报表" in html
    assert "按匹配度优先 · 按资讯类型分组" in html
    # Phase 6b — AI optimise + template + history + naming-save tokens.
    assert 'api("POST", "/radar/ai-suggest"' in html
    assert 'api("GET", "/radar/library"' in html
    assert 'api("POST", "/radar/library"' in html
    assert 'api("DELETE", "/radar/library/"' in html
    for key in (
        "radar.template",
        "radar.ai",
        "radar.history",
        "radar.save.title",
        "radar.save.placeholder",
    ):
        assert key in html, f"Radar i18n key missing: {key}"

    # Settings-bottom Agent tools hint surfaces the 7 tools without a top-level tab.
    assert "AskTab" not in html
    for tool in (
        "fin_pulse_create",
        "fin_pulse_status",
        "fin_pulse_list",
        "fin_pulse_cancel",
        "fin_pulse_settings_get",
        "fin_pulse_settings_set",
        "fin_pulse_search_news",
    ):
        assert tool in html, f"Ask tab missing tool: {tool}"

    # Digests/Radar expose schedule/channel integration; Settings no longer owns those cards.
    assert 'api("GET", "/scheduler/channels"' in html
    assert 'api("GET", "/available-channels"' in html
    assert 'api("POST", "/schedules"' in html
    assert "IM Channels" not in html and "═══════ IM Channels" not in html
    assert "Scheduled Tasks" not in html and "═══════ Scheduled Tasks" not in html
    assert "function scheduleCronFromForm" in html
    assert "定时任务模板" not in html
    assert "已配置定时任务" not in html
    assert "chat_id for " not in html
    assert "newsnow.mode" in html and "newsnow.api_url" in html
    assert "settings.newsnow.step1" in html
    assert "settings.newsnow.step2" in html
    assert "settings.newsnow.step3" in html
    # P1 — schedule templates (morning / noon / evening / radar).
    for tpl in ("morning", "noon", "evening", "radar"):
        assert f"settings.schedules.tpl.{tpl}" in html, f"schedule tpl i18n missing: {tpl}"

    # Digest plans are owned by fin-pulse now; only radar still uses the host schedule dialog.
    assert '/schedules/" + s.id + "/trigger' not in html
    assert '/schedules/" + s.id + "/toggle' not in html
    assert '"DELETE", "/schedules/" + s.id' not in html
    # P2 — the redirect-to-host button and read-only banner must have
    # been removed now that the in-page dialog is authoritative.
    assert "settings.schedules.open_host" not in html, (
        "open_host redirect affordance should be gone"
    )
    assert "settings.schedules.read_only" not in html, "read-only preview banner should be gone"
    assert "settings.channels.desc" not in html
    # P2 — NewsNow defaults to the public aggregator: the pre-filled
    # upstream URL and the 300-second rate-limit floor ship embedded in
    # the HTML bundle.
    assert "https://newsnow.busiyi.world/api/s" in html
    assert "NEWSNOW_PUBLIC_MIN_INTERVAL_S" in html
    assert "newsnow.min_interval_s" in html

    # P1 — global "no IM channel" banner must only live inside the
    # Settings IM-channels card, not at the App shell level.
    assert "showChannelBanner" not in html, (
        "the legacy App-shell channel banner should have been removed"
    )

    # Today hybrid-ingest UX — inline result drawer, smart toast, and
    # split-button single-source ingest must all be wired up.
    for key in (
        "today.ingest.done.green",
        "today.ingest.done.amber",
        "today.drawer.title",
        "today.drawer.via.newsnow",
        "today.drawer.via.direct",
        "today.drawer.via.cooldown",
        "today.list.ingest.current",
    ):
        assert key in html, f"hybrid Today i18n missing: {key}"
    # The drawer component + split-button dropdown markup.
    assert "IngestDrawer" in html
    assert "ingest-split" in html
    assert 'api("POST", "/ingest/source/"' not in html or ('"/ingest/source/"' in html), (
        "single-source endpoint wiring expected"
    )
    assert "/ingest/source/" in html, (
        "Today tab must expose the single-source /ingest/source/{id} call"
    )
    # Spinner + indeterminate progress styling tokens.
    assert "fp-spin" in html
    assert "fp-progress" in html
    # The old 8-second poll MUST be gone (a plain comment about it is
    # allowed; an actual ``setInterval(load`` invocation is not).
    assert "setInterval(load" not in html, "the legacy 8s ingest poll should have been removed"
