"""Per-commit hand-written LOC guard for the OpenAkita revamp.

The P-RC-2 audit (T1) tightened continuation plan section 0.4
from "<= 400 LOC per commit" to a two-threshold gate so the
operator notices the cap approaching before sliding into it.
There is intentionally no git pre-commit hook; this script is
run manually before every commit per the discipline reminder in
``docs/revamp/PROGRESS_LEDGER.md``.

Threshold semantics (N12, G-RC-5 P-RC-5 audit clarification)::

    total < 380   -> prints "ok: ...",     exits 0 (proceed)
    380 <= t < 400 -> prints "WARN: ...",   exits 0 (proceed -- stop
                                            and consider splitting)
    400 <= total   -> prints "REJECT: ...", exits 1 (block; split
                                            this commit before
                                            recording it)

Earlier wording in the gate notes referred to ``380 LOC`` as a
single cap; that was imprecise. The two-threshold behaviour above
(WARN at 380, REJECT at 400) is the source of truth and matches
the ``WARN_THRESHOLD`` / ``REJECT_THRESHOLD`` constants below.

Hand-written LOC = ``added + removed`` across files NOT in the
auto-generated set: ``package-lock.json`` (any tree), any
``*.lock`` / ``*.svg``, and ``docs/revamp/*.json`` baselines.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

WARN_THRESHOLD = 380
REJECT_THRESHOLD = 400

RESULT_OK = "ok"
RESULT_WARN = "warn"
RESULT_REJECT = "reject"


@dataclass(frozen=True)
class CommitGuardResult:
    """Outcome of a single guard run."""

    total_loc: int
    counted_files: list[str]
    skipped_files: list[str]
    classification: str

    @property
    def exit_code(self) -> int:
        return 1 if self.classification == RESULT_REJECT else 0


def _is_autogenerated(path: str) -> bool:
    p = path.replace("\\", "/")
    name = p.rsplit("/", 1)[-1]
    if name == "package-lock.json":
        return True
    if name.endswith((".lock", ".svg")):
        return True
    if p.startswith("docs/revamp/") and name.endswith(".json"):
        return True
    return False


def _parse_numstat(numstat: str) -> list[tuple[int, int, str]]:
    """Parse ``git diff --numstat`` text into ``(added, removed, path)``.

    Binary diffs (``-\\t-``) and rename arrows (``old -> new``) are
    handled defensively.
    """
    out: list[tuple[int, int, str]] = []
    for raw in numstat.splitlines():
        line = raw.rstrip()
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        added_s, removed_s, path = parts[0], parts[1], "\t".join(parts[2:])
        if added_s == "-" or removed_s == "-":
            continue
        try:
            added = int(added_s)
            removed = int(removed_s)
        except ValueError:
            continue
        if " -> " in path:
            path = path.split(" -> ", 1)[1].strip("{}")
        out.append((added, removed, path))
    return out


def evaluate(numstat: str) -> CommitGuardResult:
    """Classify a numstat blob. Pure / no subprocess; easy to test."""
    total = 0
    counted: list[str] = []
    skipped: list[str] = []
    for added, removed, path in _parse_numstat(numstat):
        if _is_autogenerated(path):
            skipped.append(path)
            continue
        total += added + removed
        counted.append(path)
    if total >= REJECT_THRESHOLD:
        cls = RESULT_REJECT
    elif total >= WARN_THRESHOLD:
        cls = RESULT_WARN
    else:
        cls = RESULT_OK
    return CommitGuardResult(total, counted, skipped, cls)


def _run_git_numstat(repo: Path) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), "diff", "--cached", "--numstat"],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"git diff failed (exit={proc.returncode}): {proc.stderr.strip()}"
        )
    return proc.stdout


def _format_report(r: CommitGuardResult) -> str:
    if r.classification == RESULT_REJECT:
        head = (
            f"REJECT: staged diff is {r.total_loc} hand-written LOC "
            f"(>= {REJECT_THRESHOLD}); split this commit before recording it."
        )
    elif r.classification == RESULT_WARN:
        head = (
            f"WARN: staged diff is {r.total_loc} hand-written LOC "
            f"(>= {WARN_THRESHOLD}); approaching the {REJECT_THRESHOLD} cap."
        )
    else:
        head = (
            f"ok: staged diff is {r.total_loc} hand-written LOC "
            f"(< {WARN_THRESHOLD})."
        )
    if r.skipped_files:
        head += "\n  skipped (auto-generated): " + ", ".join(r.skipped_files[:10])
    return head


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--staged", action="store_true", help="(default)")
    parser.add_argument(
        "--repo", type=Path, default=Path.cwd(), help="Repo root."
    )
    args = parser.parse_args(argv)
    numstat = _run_git_numstat(args.repo)
    result = evaluate(numstat)
    print(_format_report(result))
    return result.exit_code


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
