"""Creative image-mode exporter for ppt-maker.

This path intentionally trades editability for stronger visual consistency by
rendering each slide as a full-page PNG and embedding it into a PPTX.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from ppt_exporter import PptxExportError


class CreativeImageExporter:
    """Create a PPTX whose slides are full-page generated images."""

    def export(self, slides_ir: dict[str, Any], output_path: str | Path) -> Path:
        try:
            from PIL import Image, ImageDraw, ImageFont
            from pptx import Presentation
            from pptx.util import Inches
        except ModuleNotFoundError as exc:
            raise PptxExportError("Creative image mode requires Pillow and python-pptx.") from exc

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        asset_dir = path.parent / f"{path.stem}_creative_assets"
        asset_dir.mkdir(parents=True, exist_ok=True)

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)
        blank = prs.slide_layouts[6]
        theme = self._theme(slides_ir)
        for slide_ir in slides_ir.get("slides", []):
            png_path = self._render_png(slide_ir, asset_dir, theme, Image, ImageDraw, ImageFont)
            slide = prs.slides.add_slide(blank)
            slide.shapes.add_picture(
                str(png_path), 0, 0, width=prs.slide_width, height=prs.slide_height
            )
            notes = slide_ir.get("notes") or (slide_ir.get("content") or {}).get("speaker_note")
            if notes:
                slide.notes_slide.notes_text_frame.text = str(notes)
        if not prs.slides:
            raise PptxExportError("Cannot export an empty creative deck")
        prs.save(path)
        return path

    def _render_png(
        self,
        slide_ir: dict[str, Any],
        asset_dir: Path,
        theme: dict[str, str],
        Image,
        ImageDraw,
        ImageFont,
    ) -> Path:
        width, height = 1280, 720
        background = theme.get("background_color") or "#FFFFFF"
        primary = theme.get("primary_color") or "#3457D5"
        secondary = theme.get("secondary_color") or "#172033"
        accent = theme.get("accent_color") or "#FFB000"
        image = Image.new("RGB", (width, height), background)
        draw = ImageDraw.Draw(image)
        draw.rectangle((0, 0, width, 92), fill=secondary)
        draw.rectangle((0, 92, width, 102), fill=accent)
        title_font = self._font(ImageFont, 44, bold=True)
        body_font = self._font(ImageFont, 26)
        small_font = self._font(ImageFont, 18)
        title = str(slide_ir.get("title") or "")
        draw.text((70, 28), title[:42], fill="white", font=title_font)
        content = slide_ir.get("content") or {}
        body = content.get("body") or content.get("subtitle") or ""
        y = 150
        if body:
            for line in textwrap.wrap(str(body), width=36)[:3]:
                draw.text((80, y), line, fill=secondary, font=body_font)
                y += 38
            y += 20
        bullets = content.get("bullets") or content.get("items") or content.get("findings") or []
        for bullet in bullets[:6]:
            draw.ellipse((86, y + 10, 100, y + 24), fill=primary)
            for line in textwrap.wrap(str(bullet), width=44)[:2]:
                draw.text((120, y), line, fill=secondary, font=body_font)
                y += 34
            y += 12
        draw.text(
            (80, 665), "Creative image mode · generated by OpenAkita", fill=primary, font=small_font
        )
        out = asset_dir / f"{slide_ir.get('id', 'slide')}.png"
        image.save(out)
        return out

    @staticmethod
    def _font(ImageFont, size: int, *, bold: bool = False):
        candidates = [
            "C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc",
            "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        ]
        for candidate in candidates:
            try:
                return ImageFont.truetype(candidate, size=size)
            except OSError:
                continue
        return ImageFont.load_default()

    @staticmethod
    def _theme(slides_ir: dict[str, Any]) -> dict[str, str]:
        first = next(iter(slides_ir.get("slides", [])), {})
        theme = first.get("theme") or {}
        return {
            "primary_color": theme.get("primary_color") or "#3457D5",
            "secondary_color": theme.get("secondary_color") or "#172033",
            "accent_color": theme.get("accent_color") or "#FFB000",
            "background_color": theme.get("background_color") or "#FFFFFF",
        }
